[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com https://googleads.g.doubleclick.net https://www.googleadservices.com https://td.doubleclick.net; img-src 'self' data: https://www.google.com https://www.google-analytics.com https://googleads.g.doubleclick.net https://www.googleadservices.com; connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://googletagmanager.com https://www.googletagmanager.com https://td.doubleclick.net https://googleads.g.doubleclick.net; frame-src https://td.doubleclick.net https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
