[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = ""
    X-Content-Security-Policy = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
